# Generated by Django 4.1.4 on 2025-07-10 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='students.student'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('student', 'course')},
        ),
    ]
