# Generated by Django 4.1.4 on 2025-08-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('course_interest', models.CharField(choices=[('engineering', 'Engineering'), ('medical', 'Medical'), ('management', 'Management'), ('arts', 'Arts & Humanities'), ('science', 'Science'), ('commerce', 'Commerce'), ('law', 'Law'), ('pharmacy', 'Pharmacy'), ('nursing', 'Nursing'), ('agriculture', 'Agriculture'), ('abroad', 'Study Abroad'), ('other', 'Other')], max_length=20)),
                ('current_education', models.CharField(blank=True, help_text='Current class/degree', max_length=100)),
                ('preferred_location', models.CharField(blank=True, help_text='Preferred study location', max_length=100)),
                ('message', models.TextField(blank=True, help_text='Additional message or specific requirements')),
                ('preferred_contact_time', models.CharField(choices=[('morning', 'Morning (9 AM - 12 PM)'), ('afternoon', 'Afternoon (12 PM - 5 PM)'), ('evening', 'Evening (5 PM - 8 PM)'), ('anytime', 'Anytime')], default='anytime', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('in_progress', 'In Progress'), ('converted', 'Converted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('assigned_to', models.CharField(blank=True, help_text='Staff member assigned to this enquiry', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Internal notes for staff')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contacted_at', models.DateTimeField(blank=True, help_text='When the enquiry was first contacted', null=True)),
            ],
            options={
                'verbose_name': 'Enquiry',
                'verbose_name_plural': 'Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
