# Generated by Django 5.0.1 on 2026-01-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0002_studentinquiry_delete_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinquiry',
            name='inquiry_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('quick', 'Quick')], default='standard', max_length=20),
        ),
    ]
