# Generated by Django 4.1.4 on 2025-07-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_add_new_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='annual_fee',
        ),
        migrations.RemoveField(
            model_name='course',
            name='total_fee',
        ),
        migrations.AlterField(
            model_name='course',
            name='degree_type',
            field=models.CharField(choices=[('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate'), ('diploma', 'Diploma'), ('certificate', 'Certificate'), ('doctorate', 'Doctorate')], max_length=20),
        ),
    ]
