# Generated by Django 4.1.4 on 2025-07-28 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_annual_fee_remove_course_total_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='affiliated',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='college',
            name='courses',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='college',
            name='institution_type',
            field=models.CharField(blank=True, choices=[('government', 'Government'), ('private', 'Private'), ('deemed', 'Deemed')], max_length=20),
        ),
        migrations.AddField(
            model_name='college',
            name='ranking',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='short_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_list', to='courses.college'),
        ),
    ]
