# Generated by Django 5.0.1 on 2025-12-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='about_text',
            field=models.TextField(blank=True, help_text="Detailed description for 'About' section"),
        ),
        migrations.AddField(
            model_name='college',
            name='quick_stats',
            field=models.JSONField(blank=True, default=dict, help_text="JSON object for quick stats e.g., {'campus_size': '100 acres', 'total_students': '5000'}"),
        ),
    ]
