# Generated by Django 5.0.1 on 2025-12-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_college_about_text_college_quick_stats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='course',
            name='college',
        ),
        migrations.AddField(
            model_name='course',
            name='colleges',
            field=models.ManyToManyField(blank=True, related_name='courses', to='courses.college'),
        ),
    ]
