# Generated by Django 5.0.1 on 2026-01-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_college_courses_remove_course_college_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('engineering', 'Engineering'), ('medical', 'Medical'), ('management', 'Management'), ('arts', 'Arts'), ('law', 'Law'), ('pharmacy', 'Pharmacy'), ('agriculture', 'Agriculture'), ('architecture', 'Architecture')], max_length=20),
        ),
    ]
